### ISSUE TITLE
Binding: Error: CreatePersistentTrackingPosition: Exception: System.ArgumentException: Must be non-negative.

### ISSUE THREAD

**Issue by gasparnagy** [specsolutions/deveroom-feedback#10]
After discovery, the following error is reported in the output pane

```
Error: CreatePersistentTrackingPosition: Exception: System.ArgumentException: Must be non-negative.
Parameter name: startIndex
   at Microsoft.VisualStudio.Text.Implementation.PersistentSpanFactory.Create(String filePath, Int32 startLine, Int32 startIndex, Int32 endLine, Int32 endIndex, SpanTrackingMode trackingMode)
   at Deveroom.VisualStudio.ProjectSystem.VsProjectSystem.CreatePersistentTrackingPosition(String filePath, Int32 line, Int32 column) in W:\Deveroom\Deveroom.VisualStudio\Deveroom.VisualStudio.Package\ProjectSystem\VsProjectSystem.cs:line 95
```

In the log file, the line numbers of some of the step definitions are wrong: 
```
{
      "type": "Then",
      "regex": "^a tag \"(.*)\" is added to the scenario in the local workspace$",
      "method": "Steps.Then_a_tag_TAG_is_added_to_the_scenario_in_the_local_workspace(String)",
      "paramTypes": "s",
      "sourceLocation": "#2|16707566|0"
},
```

**Comment by gasparnagy** [comment]
fixed
