### ISSUE TITLE
Bindings: Method not found: ConnectorResult.set_Warnings

### ISSUE THREAD

**Issue by gasparnagy** [specsolutions/deveroom-feedback#4]
Performing binding discovery of a project provides: 

```
Warning: RecalculateBindingRegistryInternal: Error during binding discovery. 
Command executed:
  [...]\bin\Debug> [...]\EXTENSIONS\NUUJ25EQ.LKM\Connectors\V1\deveroom-specflow-v1.exe discovery [...]
Exit code: 4
Message: error: Method not found: 'Void Deveroom.VisualStudio.SpecFlowConnector.Models.ConnectorResult.set_Warnings(System.String[])'.

Server stack trace: 
   at Deveroom.VisualStudio.SpecFlowConnector.Discovery.BaseDiscoverer.DiscoverInternal(String testAssemblyPath, String configFilePath)
   at Deveroom.VisualStudio.SpecFlowConnector.Discovery.BaseDiscoverer.Discover(String testAssemblyPath, String configFilePath)
   at System.Runtime.Remoting.Messaging.StackBuilderSink._PrivateProcessMessage(IntPtr md, Object[] args, Object server, Object[]& outArgs)
   at System.Runtime.Remoting.Messaging.StackBuilderSink.SyncProcessMessage(IMessage msg)

Exception rethrown at [0]: 
   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at Deveroom.VisualStudio.SpecFlowConnector.Discovery.ISpecFlowDiscoverer.Discover(String testAssembly, String configFilePath)
   at Deveroom.VisualStudio.SpecFlowConnector.Discovery.DiscoveryProcessor.Process()
   at Deveroom.VisualStudio.SpecFlowConnector.ConsoleRunner.EntryPoint(String[] args)
```

Self note: SpecSync Specs

**Comment by gasparnagy** [comment]
was caused by wrongly setup environment
