### ISSUE TITLE
.NET Core Bindings: Project dependency load issue

### ISSUE THREAD

**Issue by gasparnagy** [specsolutions/deveroom-feedback#5]
Discovering dependencies of a .NET Core 2.1 test assembly, where one of the types inherit from `WebApplicationFactory<T>` leads to error:

```
Warning: RecalculateBindingRegistryInternal: Error during binding discovery. 
Command executed:
  [...]\bin\Debug\netcoreapp2.1> [...]\NUUJ25EQ.LKM\Connectors\V2\deveroom-specflow-v2.exe discovery [...]
Exit code: 4
Message: error: Exception has been thrown by the target of an invocation. -> Unable to load one or more of the requested types.
Could not load file or assembly 'Microsoft.AspNetCore.Hosting.Abstractions, Version=2.1.1.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'. The system cannot find the file specified.
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Deveroom.VisualStudio.SpecFlowConnector.ReflectionExtensions.ReflectionCallMethod[T](Object obj, String methodName, Type[] parameterTypes, Object[] args) in W:\Devero\Deveroom.VisualStudio\Deveroom.VisualStudio.SpecFlowConnector.V2\ReflectionExtensions.cs:line 17
   at Deveroom.VisualStudio.SpecFlowConnector.Discovery.ReflectionSpecFlowDiscoverer.Discover(Assembly testAssembly, String testAssemblyPath, String configFilePath) in W:\Devero\Deveroom.VisualStudio\Deveroom.VisualStudio.SpecFlowConnector.V2\Discovery\ReflectionSpecFlowDiscoverer.cs:line 25
   at Deveroom.VisualStudio.SpecFlowConnector.Discovery.DiscoveryProcessor.Process() in W:\Devero\Deveroom.VisualStudio\Deveroom.VisualStudio.SpecFlowConnector.V2\Discovery\DiscoveryProcessor.cs:line 41
   at Deveroom.VisualStudio.SpecFlowConnector.ConsoleRunner.EntryPoint(String[] args) in W:\Devero\Deveroom.VisualStudio\Deveroom.VisualStudio.SpecFlowConnector.V2\ConsoleRunner.cs:line 27
```

Self note: B1-pre

**Comment by gasparnagy** [comment]
Fixed in v1.0.3. The problem was caused by not loading the compile-only ASP.NET Core dependencies.
